#!/usr/bin/env python3
"""Merge auto + manual vibe scores, add percentiles, bake into index.html.

  vibes-auto.json    generated, per-axis raw scores
  vibes-manual.json  hand corrections, never written by the scorer

Manual wins per axis, partially: correcting `compete` alone leaves the other
five axes on their auto values. Each axis records its source so the UI can mark
hand-verified games.

Raw scores are stored; percentiles are derived here at build time, because a
percentile shifts every time a game joins the collection and a raw score does
not. Ties share a percentile -- with 40% of the collection tied at zero on
social and compete that matters, see README.

Writes a VIBES block into index.html between the marker comments, so re-running
is idempotent.
"""
import json, os, re, sys, argparse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
AUTO = os.path.join(HERE, "vibes-auto.json")
MANUAL = os.path.join(HERE, "vibes-manual.json")
PAGE = os.path.join(ROOT, "index.html")

AXES = ["cozy", "social", "playful", "compete", "intense", "thinky"]
START = "/* VIBES:START -- generated by vibes/build_vibes.py, do not edit by hand */"
END = "/* VIBES:END */"


def percentiles(values):
    """Average-rank percentile, 0-100. Tied values share a percentile."""
    order = sorted(values)
    n = len(order)
    out = {}
    for v in set(order):
        lo = order.index(v)
        hi = n - 1 - order[::-1].index(v)
        out[v] = round(100.0 * ((lo + hi) / 2.0) / (n - 1)) if n > 1 else 50
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="report only, do not write index.html")
    a = ap.parse_args()

    auto = json.load(open(AUTO, encoding="utf-8"))
    manual = json.load(open(MANUAL, encoding="utf-8")) if os.path.exists(MANUAL) else {}
    cache = json.load(open(os.path.join(HERE, "bgg-cache.json"), encoding="utf-8"))

    merged = {}
    for gid in set(auto) | set(manual):
        m = manual.get(gid, {})
        rec, src = {}, {}
        for ax in AXES:
            if ax in m:
                rec[ax], src[ax] = int(m[ax]), "manual"
            elif gid in auto and ax in auto[gid]:
                rec[ax], src[ax] = auto[gid][ax], "auto"
        if not rec:
            continue
        rec["src"] = src
        if m.get("note"):
            rec["note"] = m["note"]
        # Player-count poll result, for the match score's hard filter and the
        # best-player bar. Spec 6.1 prefers this over raw min/max.
        best = [int(b) for b in (cache.get(gid, {}).get("best") or []) if str(b).isdigit()]
        if best:
            rec["bestP"] = best
        merged[gid] = rec

    # Percentiles across the collection, per axis.
    pct = {ax: percentiles([r[ax] for r in merged.values() if ax in r]) for ax in AXES}
    for r in merged.values():
        r["pct"] = {ax: pct[ax][r[ax]] for ax in AXES if ax in r}

    manual_axes = sum(1 for r in merged.values() for s in r["src"].values() if s == "manual")
    manual_games = sum(1 for r in merged.values() if "manual" in r["src"].values())
    print(f"merged {len(merged)} games | {manual_games} with hand corrections "
          f"({manual_axes} axes overridden)")

    if a.check:
        return

    if not os.path.exists(PAGE):
        sys.exit(f"missing {PAGE}")
    page = open(PAGE, encoding="utf-8").read()
    block = (START + "\nconst VIBES = " +
             json.dumps(merged, ensure_ascii=False, sort_keys=True, separators=(",", ":")) +
             ";\n" + END)

    if START in page:
        page = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block,
                      page, flags=re.S)
    else:
        # First run: drop it in immediately after the GAMES array.
        anchor = page.index("\n];", page.index("const GAMES = [")) + 3
        page = page[:anchor] + "\n\n" + block + page[anchor:]

    with open(PAGE, "w", encoding="utf-8", newline="") as f:
        f.write(page)
    print(f"baked VIBES into {os.path.relpath(PAGE, ROOT)}")


if __name__ == "__main__":
    main()
